variable "region" {
  description = "Specfies the region in which this resouce will be created in"
  type        = string
  default     = "af-south-1"
}

variable "eventBridge_rule_name" {
  description = "Specifies the name of the eventBridge rule"
  type        = string
}

variable "eventBridge_rule_description" {
  description = "Specifies the description of the eventBridge rule"
  type        = string
}

variable "eventBridge_rule_event_pattern" {
  description = "Specifies the event pattern to match"
  type        = string
}

variable "is_eventBridge_rule_enabled" {
  description = "Specifies whether the eventBridge rule is enabled"
  type        = bool
  default     = true
}

variable "eventBridge_tags" {
  description = "Specifies the tags (key, value pairs) to be associated with the eventBridge rule"
  type        = map(string)
}

variable "run_command_targets" {
  description = "Specifies the targets for the run command"
  type        = map(string, list(string))
}

variable "is_eventBridge_api_destination" {
  description = "Specifies whether to create an eventBridge api destination"
  type        = bool
  default     = false
}

variable "eventBridge_api_destination_name" {
  description = "Specifies the name of the eventBridge api destination"
  type        = string
  default     = null
}

variable "eventBridge_api_destination_description" {
  description = "Specifies the description of the eventBridge api destination"
  type        = string
  default     = null
}

variable "eventBridge_api_invocation_endpoint" {
  description = "URL endpoint to invoke as a target. This could be a valid endpoint generated by a partner service. You can include " * " as path parameters wildcards to be set from the Target HttpParameters."
  type        = string
  default     = null
}

variable "eventBridge_api_http_method" {
  description = "Select the HTTP method used for the invocation endpoint, such as GET, POST, PUT, etc."
  type        = string
  default     = null
}

variable "eventBridge_api_invocation_rate_limit_per_second" {
  description = "Enter the maximum number of invocations per second to allow for this destination. Enter a value greater than 0 (default 300)."
  type        = number
  default     = null
}

variable "eventBridge_connection_name" {
  description = "Specifies the name of the eventBridge connection"
  type        = string
  default     = null
}

variable "eventBridge_connection_description" {
  description = "Specifies the description of the eventBridge connection"
  type        = string
  default     = null
}

variable "eventBridge_connection_authorization_type" {
  description = "Choose the type of authorization to use for the connection. One of API_KEY,BASIC,OAUTH_CLIENT_CREDENTIALS."
  type        = string
  default     = "BASIC"
}

variable "eventBridge_connection_auth_basic_username" {
  description = "Specifies the username for basic authorization"
  type        = string
  default     = null
}

variable "eventBridge_connection_auth_basic_password" {
  description = "Specifies the password for basic authorization"
  type        = string
  default     = null
}

variable "eventBridge_connection_auth_params_api_key" {
  description = "Specifies the api key for api key authorization"
  type        = string
  default     = null
}

variable "eventBridge_connection_auth_params_api_value" {
  description = "Specifies the api value for api key authorization"
  type        = string
  default     = null
}

variable "eventBridge_rule_schedule_expression" {
  description = "Specifies the schedule expression for the eventBridge rule"
  type        = string
  default     = null
}

variable "eventBridge_target_arn" {
  description = "Specifies the arn of the target"
  type        = string
}

variable "eventBridge_target_id" {
  description = "Specifies the unique target assignment ID"
  type        = string
}

variable "eventBridge_http_target_header_parameters" {
  description = "Specifies the header parameters for the http target"
  type        = map(string)
  default     = null
}

variable "eventBridge_http_target_path_parameter_values" {
  description = "The list of values that correspond sequentially to any path variables in your endpoint ARN"
  type        = list(string)
  default     = null
}

variable "eventBridge_http_target_query_string_parameters" {
  description = "Represents keys/values of query string parameters that are appended to the invoked endpoint."
  type        = map(string)
  default     = null
}

variable "eventBridge_is_http_targets" {
  description = "Specifies whether to create http target in the event target"
  type        = bool
  default     = false
}

variable "eventBridge_role_arn" {
  description = "Specifies The arn of the IAM role to be used for this target when the rule is triggered. Required if ecs_target is used or target in arn is EC2 instance, Kinesis data stream, Step Functions state machine, or Event Bus in different account or region."
  type        = string
  default     = null
}

variable "eventBridge_connection_auth_parameters" {
  description = "Specifies if we will be creating auth parameters for the eventBridge connection"
  type        = bool
  default     = false
}

variable "eventBridge_connnection_is_auth_basic" {
  description = "Specifies if we will be creating basic auth parameters for the eventBridge connection"
  type        = bool
  default     = false
}

variable "eventBridge_connnection_is_auth_api_key" {
  description = "Specifies if we will be creating api key auth parameters for the eventBridge connection"
  type        = bool
  default     = false
}

variable "eventBridge_bus_name" {
  description = "Specifies the name of the eventBridge bus"
  type        = string
}

variable "eventBridge_is_connection" {
  description = "Specifies whether to create an eventBridge connection"
  type        = bool
  default     = false
}

variable "eventBridge_rule_role_name" {
  description = "Specifies the name of the role for the eventBridge rule"
  type        = string
}