FROM jenkins/jenkins

USER root

# Install Nodejs
RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

# Install Terraform
RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip && \
    unzip terraform_1.7.0_linux_amd64.zip && \
    mv terraform /usr/local/bin && \
    rm terraform_1.7.0_linux_amd64.zip


# Install Terragrunt
RUN wget -O /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.34.1/terragrunt_linux_amd64 && \
    chmod +x /usr/local/bin/terragrunt


# Install Python
RUN apt-get install -y python3


#Install pip3
RUN apt-get install -y python3-pip

# Install AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
   ./aws/install

# Install Docker
RUN apt-get update && \
    apt-get install -y docker.io

# Install Git
RUN apt-get update && \
    apt-get install -y git

