FROM jenkins/jenkins:lts-jdk11

USER root

# Add Jenkins user to sudoers list
RUN echo "jenkins ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

RUN apt-get update && \
    apt-get install -y \
        git \
        maven \
        python3 \
        python3-pip \
        golang \
        gcc \
        make \
        binutils \
        build-essential \
        nfs-common \
        dnf

        
# Install wget
RUN apt-get install -y wget

RUN apt-get install -y ca-certificates \
        groff \
        less \
        unzip \
        jq \
        && apt-get clean

RUN apt-get uodate && \
    apt-get -y install git binutils rustc cargo pkg-config libssl-dev

RUN dnf install dnf-plugins-core -y        

RUN dnf config-manager --add-repo=https://cdn.amazonlinux.com/2/core/latest/x86_64/extras

RUN dnf install -y amazon-efs-utils



# Install Terraform
RUN wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip && \
    unzip terraform_1.7.0_linux_amd64.zip && \
    mv terraform /usr/local/bin && \
    rm terraform_1.7.0_linux_amd64.zip

# Install botocore
RUN apt-get install -y python3-botocore

# Optional: Install additional plugins using the Jenkins Plugin Manager
RUN wget -q -O - https://updates.jenkins.io/current/update-center.json


# Set time and region to Africa/Johannesburg
RUN ln -sf /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime && \
    echo "Africa/Johannesburg" > /etc/timezone


RUN echo /var/jenkins_home/secrets/initialAdminPassword  

EXPOSE 8080
EXPOSE 80
EXPOSE 443
EXPOSE 5432
EXPOSE 3306
EXPOSE 2999