---
- debug:
    msg: "BEGIN - Deployment of {{ module_dependency }} started"

- name: Run terragrunt init for "{{ module_dependency }}"
  command: terragrunt init
  args:
    chdir: "{{ module_dependency }}"

- name: Check terragrunt confguration formatting for "{{ module_dependency }}"
  command: terragrunt fmt
  args:
    chdir: "{{ module_dependency }}"

- name: Validate terragrunt configuration for  "{{ module_dependency }}"
  command: terragrunt validate
  args:
    chdir: "{{ module_dependency }}"

- name: Run terragrunt plan for "{{ module_dependency }}"
  command: terragrunt plan
  args:
    chdir: "{{ module_dependency }}"
  register: terragrunt_plan_output

- name: Display terragrunt plan output
  debug:
    var: terragrunt_plan_output.stdout_lines

- name: Run terragrunt apply for "{{ module_dependency }}"
  command: terragrunt apply --auto-approve
  args:
    chdir: "{{ module_dependency }}"

- name: Get outputs from "{{ module_dependency }}"
  command: terragrunt output
  args:
    chdir: "{{ module_dependency }}"
  register: terragrunt_outputs

- name: Display terragrunt apply output
  debug:
    var: terragrunt_outputs.stdout_lines

- name: Wait for "{{ module_dependency }}" to be up
  pause:
    seconds: 60

- name: validate resources
  shell: ../scripts/verify_resources.sh "{{ terragrunt_outputs.stdout_lines | quote}}"

- debug:
    msg: "COMPLETED - Deployment of {{ module_dependency }} completed"
